### ISSUE TITLE
Make this an xbps package

### ISSUE THREAD

**Issue by adbrown101** [bahamas10/bash-vsv#3]
I am not sure if you have looked into this, but it would be good as an xbps package. This recipe worked for me on my local machine. NB I had to add an MIT licence file in the vsv directory.
<pre>
# Template file for 'vsv'
pkgname=vsv
version=1.3.1
revision=1
archs=noarch
short_desc="Manage and view runit services"
maintainer="<......>"
license="MIT"
homepage="https://github.com/bahamas10/vsv"
distfiles="https://github.com/bahamas10/vsv/archive/v${version}.tar.gz"
checksum=1f0b60bd969ea11be80e2fea7e5b7f7b74baec8d9ef1c7ea2a2daf7363c7b348

do_install() {
    vbin vsv
    vman man/vsv.8
    vlicense ${FILESDIR}/LICENSE
}
</pre>

**Comment by bahamas10** [comment]
oh, I like this idea a lot! I'll look into this... my initial concern is that I called this `vsv`, which is the `Void Service Manager` - which is probably a poor name at best as:

1. it's for runit, not void specifically, and
2. it's not officially a "void" package

so hopefully that isn't an issue when requesting this be added to void-packages - but i'll take a look. ty for this

**Comment by bahamas10** [comment]
https://github.com/void-linux/void-packages/pull/17979

**Comment by Piraty** [comment]
You're right, it's not  specific to Void Linux, so I vote for a more generic name (which i can't came up with, other than `runitctl`, which i hope you won't pick  :stuck_out_tongue_closed_eyes: !!)

Edit: since it wraps `sv`, take that as prefix?

**Comment by bahamas10** [comment]
It's live! :)

```
$ sudo xbps-install vsv

Name Action    Version           New version            Download size
vsv  install   -                 1.3.2_1                6276B 

Size to download:              6788B
Size required on disk:          23KB
Space available on disk:       288GB

Do you want to continue? [Y/n] 

[*] Downloading packages
vsv-1.3.2_1.noarch.xbps.sig: 512B [avg rate: 11MB/s]
vsv-1.3.2_1.noarch.xbps: 6276B [avg rate: -- stalled --]
vsv-1.3.2_1: verifying RSA signature...

[*] Collecting package files
vsv-1.3.2_1: collecting files...

[*] Unpacking packages
vsv-1.3.2_1: unpacking ...

[*] Configuring unpacked packages
vsv-1.3.2_1: configuring ...
vsv-1.3.2_1: installed successfully.

1 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.
$ vsv -V
v1.3.2
```

**Comment by adbrown101** [comment]
Dave,
I thought it would get in, it is a good project. I think the requirements for a project to be accepted in the xbps-src manual seem quite flexible.
I will uninstall the version from my private repo and install from master
regards
Alan

    On Thursday, 9 January 2020, 03:12:52 GMT, Dave Eddy <notifications@github.com> wrote:  
 
 
It's live! :)
$ sudo xbps-install vsv

Name Action    Version           New version            Download size
vsv  install   -                 1.3.2_1                6276B 

Size to download:              6788B
Size required on disk:          23KB
Space available on disk:       288GB

Do you want to continue? [Y/n] 

[*] Downloading packages
vsv-1.3.2_1.noarch.xbps.sig: 512B [avg rate: 11MB/s]
vsv-1.3.2_1.noarch.xbps: 6276B [avg rate: -- stalled --]
vsv-1.3.2_1: verifying RSA signature...

[*] Collecting package files
vsv-1.3.2_1: collecting files...

[*] Unpacking packages
vsv-1.3.2_1: unpacking ...

[*] Configuring unpacked packages
vsv-1.3.2_1: configuring ...
vsv-1.3.2_1: installed successfully.

1 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.
$ vsv -V
v1.3.2

**Comment by bahamas10** [comment]
ty @adbrown101 

@Piraty i'm open to other names if you can think of any, but it seems like for now `vsv` is the chosen one :)

instructions added in https://github.com/bahamas10/vsv/commit/fbfc876e9f240969a478199c4a708b82d3801507
