### ISSUE TITLE
vsv defaults to no color in Alacritty terminal.

### ISSUE THREAD

**Issue by ericonr** [bahamas10/bash-vsv#8]
The way color support detection works means that the result for the alacritty terminal is wrong. It becomes necessary to add the `-c yes` flag or change the `TERM` env variable to enable colored output. Do you think it is within the scope of this project to make the detection better or should I just make an alias on my own system?

**Comment by bahamas10** [comment]
oh interesting.  i use urxvt myself, but am thinking of switching over to alacritty.  what does your `$TERM` env var look like?

**Comment by bahamas10** [comment]
I pulled up the documentation for `alacritty` and found [this](https://github.com/alacritty/alacritty/blob/master/alacritty.yml):

> ```#env:
>  # TERM variable
>  #
>  # This value is used to set the `$TERM` environment variable for
>  # each instance of Alacritty. If it is not present, alacritty will
>  # check the local terminfo database and use `alacritty` if it is
>  # available, otherwise `xterm-256color` is used.
>  #TERM: xterm-256color

I did some testing on my machine, and I think I have a patch that solves this problem.

![vsv-color](https://user-images.githubusercontent.com/1205722/74364942-1d982000-4d9b-11ea-8af6-79b482eff251.jpg)

Note that the `alacritty` env var *only* worked after the `alacritty-terminfo` package was installed (installed via the `alacritty` package).

You can test out my changes if you'd like in this branch https://github.com/bahamas10/vsv/tree/term-var

**Comment by ericonr** [comment]
I've just tested it out, and it's working well. Thanks! I believe the terminfo-alacritty package is pulled by alacritty, so it shouldn't have any trouble.

Do you need any further testing?

**Comment by bahamas10** [comment]
thank you! i just pushed it as `v1.3.4`... i'll bump it in xbps soon
